apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - image: us-south1-docker.pkg.dev/sleepr-415520/notifications/production
        name: notifications
        env:
          - name: PORT
            value: '3000'
          - name: GOOGLE_OAUTH_CLIENT_ID
            value: 850888517131-ddjufg2d8qf2vrjlhlcht2ndfsn8ug5m.apps.googleusercontent.com
          - name: SMTP_USER
            value: wilhelmcast@gmail.com
          - name: GOOGLE_OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: google
                key: clientSecret
          - name: GOOGLE_OAUTH_REFRESH_TOKEN
            valueFrom:
              secretKeyRef:
                name: google
                key: refreshTokenKey
          - name: GOOGLE_OAUTH_ACESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: google
                key: accessToken
        ports:
          - containerPort: 3000