steps:
  # Reservations
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-south1-docker.pkg.dev/sleepr-415520/reservations/production',
      '-f',
      'apps/reservations/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-south1-docker.pkg.dev/sleepr-415520/reservations/production',
    ]

  #Auth
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-south1-docker.pkg.dev/sleepr-415520/auth/production',
      '-f',
      'apps/auth/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-south1-docker.pkg.dev/sleepr-415520/auth/production',
    ]

  #Notifications
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-south1-docker.pkg.dev/sleepr-415520/notifications/production',
      '-f',
      'apps/notifications/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-south1-docker.pkg.dev/sleepr-415520/notifications/production',
    ]

  #Payments
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-south1-docker.pkg.dev/sleepr-415520/payments/production',
      '-f',
      'apps/payments/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-south1-docker.pkg.dev/sleepr-415520/payments/production',
    ]
